### ISSUE TITLE
コミュニティの運営について

### ISSUE THREAD

**Issue by gurezo** [ng-saitama/management#1]
以下の運営項目をどうするか。
- 会場費用について
  - レンタル費用と参加人数のバランスシート
- イベントサイクル

**Comment by tronperidot** [comment]
- 費用は第二回 〜 三回とこなして決めていきたいと思ってます
- イベントサイクルは会場を変えない限り確実に予約できる事もあるので最短二ヶ月周期で良いかと思ってます。それより伸ばすかどうかという話なら考えます

**Comment by gurezo** [comment]
了解です。
今週末もくもく会の時に、諸々すり合わせをしましょう！

**Comment by gurezo** [comment]
一旦二ヶ月に一度のサイクル
会場は公民館という選択肢も模索
